Tutoria 4 Modulo 2

Formatos de texto

In [1]:
#Librerias
import pandas as pd
import numpy as np
import sqlite3

In [3]:
#Leer dataset
df_mal_leido = pd.read_csv("candidatos.csv")
df_mal_leido

   candidato_id;nombre;ciudad;departamento;nivel_ingles;tecnologia_principal;salario_esperado;fecha_registro;activo
0   1;Valentina Torres;Bogotá;Cundinamarca;Avanzad...
1   2;Camilo Ríos;Medellín;Antioquia;Intermedio;Ja...
2   3;Laura Méndez;Cali;Valle del Cauca;Básico;;52...
3   4;Andrés Guzmán;Bogotá;Cundinamarca;Avanzado;P...
4   5;Daniela Ospina;Barranquilla;Atlántico;Interm...
5   6;Felipe Moreno;Medellín;Antioquia;Básico;Reac...
6   7;María José Parra;Bogotá;Cundinamarca;Avanzad...
7   8;Sebastián Vargas;Bucaramanga;Santander;Inter...
8   9;Carolina Díaz;Cali;Valle del Cauca;Básico;;3...
9   10;Juan Pablo Herrera;Bogotá;Cundinamarca;Avan...
10  11;Luisa Fernanda Castro;Medellín;Antioquia;In...
11  12;Nicolás Ramírez;Pereira;Risaralda;Básico;Ja...
12  13;Alejandra Muñoz;Bogotá;Cundinamarca;Avanzad...
13  14;David Lozano;Cartagena;Bolívar;Intermedio;R...
14  15;Natalia Suárez;Manizales;Caldas;Básico;;400...
15  16;Esteban Jiménez;Bogotá;Cundinamarca;Avanzad...
16  17;Paula Restrepo;Medellín;Antioquia;Intermedi...
17  18;Tomás Guerrero;Cali;Valle del Cauca;Básico;...
18  19;Isabella Molina;Bogotá;Cundinamarca;Avanzad...
19  20;Mateo Salcedo;Medellín;Antioquia;Intermedio...

In [9]:
#Lectura correcta
df_candidatos = pd.read_csv(
    "candidatos.csv",
    sep=";",
    encoding="utf-8", #Para leer tildes y ñ sin corrupción
    parse_dates=["fecha_registro"], #Convierta esta columna a tipo datetime aa-mm-dd
    dayfirst=True #dd/mm/yyy
)

print(f"{df_candidatos.shape[0]} filas x {df_candidatos.shape[1]} columnas cargadas")
df_candidatos.head(5)

20 filas x 9 columnas cargadas

,candidato_id,nombre,ciudad,departamento,nivel_ingles,tecnologia_principal,salario_esperado,fecha_registro,activo
0,1,Valentina Torres,Bogotá,Cundinamarca,Avanzado,Python,4500000.0,2024-01-15,True
1,2,Camilo Ríos,Medellín,Antioquia,Intermedio,JavaScript,3800000.0,2024-01-22,True
2,3,Laura Méndez,Cali,Valle del Cauca,Básico,NaN,5200000.0,2024-01-30,False
3,4,Andrés Guzmán,Bogotá,Cundinamarca,Avanzado,Python,6100000.0,2024-02-05,True
4,5,Daniela Ospina,Barranquilla,Atlántico,Intermedio,Java,NaN,2024-02-12,True

In [10]:
df_candidatos.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   candidato_id          20 non-null     int64
 1   nombre                20 non-null     str
 2   ciudad                20 non-null     str
 3   departamento          20 non-null     str
 4   nivel_ingles          20 non-null     str
 5   tecnologia_principal  17 non-null     str
 6   salario_esperado      17 non-null     float64
 7   fecha_registro        20 non-null     datetime64[us]
 8   activo                20 non-null     bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 1.4 KB

In [13]:
#Acesso a columnas individuales
df_candidatos['nombre']
df_candidatos.ciudad.head(7)

0          Bogotá
1        Medellín
2            Cali
3          Bogotá
4    Barranquilla
5        Medellín
6          Bogotá
Name: ciudad, dtype: str

In [ ]:
#Mostrar las ultimas 3 cfilas del dataframe
df_candidatos.tail(5)

,candidato_id,nombre,ciudad,departamento,nivel_ingles,tecnologia_principal,salario_esperado,fecha_registro,activo
15,16,Esteban Jiménez,Bogotá,Cundinamarca,Avanzado,Data Science,6800000.0,2024-04-22,True
16,17,Paula Restrepo,Medellín,Antioquia,Intermedio,DevOps,5100000.0,2024-04-29,False
17,18,Tomás Guerrero,Cali,Valle del Cauca,Básico,JavaScript,3400000.0,2024-05-06,True
18,19,Isabella Molina,Bogotá,Cundinamarca,Avanzado,Python,NaN,2024-05-13,True
19,20,Mateo Salcedo,Medellín,Antioquia,Intermedio,Java,4700000.0,2024-05-20,True

In [15]:
#Mostras cuantos candidatos hay por ciudad?
df_candidatos["ciudad"].value_counts()

ciudad
Bogotá          7
Medellín        5
Cali            3
Barranquilla    1
Bucaramanga     1
Pereira         1
Cartagena       1
Manizales       1
Name: count, dtype: int64

In [17]:
#Leer un dataset en forma de resumen

df_resumen = pd.read_csv(
    "candidatos.csv",
    sep=";",
    encoding="utf-8",
    #usecols [lista] le dice a pandas: venga yo solo quieor que me cargue esas 4 columnas y ya
    usecols=["candidato_id", "nombre", "tecnologia_principal", "salario_esperado"]
)

df_resumen

    candidato_id                 nombre tecnologia_principal  salario_esperado
0              1       Valentina Torres               Python         4500000.0
1              2            Camilo Ríos           JavaScript         3800000.0
2              3           Laura Méndez                  NaN         5200000.0
3              4          Andrés Guzmán               Python         6100000.0
4              5         Daniela Ospina                 Java               NaN
5              6          Felipe Moreno                React         3200000.0
6              7       María José Parra         Data Science         5800000.0
7              8       Sebastián Vargas               Python         4200000.0
8              9          Carolina Díaz                  NaN         3600000.0
9             10     Juan Pablo Herrera               DevOps         7200000.0
10            11  Luisa Fernanda Castro           JavaScript         4100000.0
11            12        Nicolás Ramírez                 Java               NaN
12            13        Alejandra Muñoz               Python         5500000.0
13            14           David Lozano                React         3900000.0
14            15         Natalia Suárez                  NaN         4000000.0
15            16        Esteban Jiménez         Data Science         6800000.0
16            17         Paula Restrepo               DevOps         5100000.0
17            18         Tomás Guerrero           JavaScript         3400000.0
18            19        Isabella Molina               Python               NaN
19            20          Mateo Salcedo                 Java         4700000.0

Bloque 2, Excel

In [19]:
#Leer Excel
df_empresas_activas = pd.read_excel(
    "empresas.xlsx",
    sheet_name="activas",
    parse_dates=["fecha_alianza"]
)

df_empresas_activas.head(5)

,empresa_id,nombre_empresa,sector,ciudad,tamaño,presupuesto_salario_max,fecha_alianza
0,101,TechColombia SAS,Tecnología,Bogotá,Startup,8000000,2023-06-01
1,102,DataFlow Analytics,Tecnología,Medellín,PYME,7500000,2023-08-15
2,103,Innovación Digital,Tecnología,Bogotá,Corporación,12000000,2023-09-01
3,104,Fintech Andina,Finanzas,Bogotá,PYME,9000000,2023-10-20
4,105,CloudServ Latam,Tecnología,Cali,Startup,6500000,2023-11-05

In [21]:
#Inactivas
#Leer Excel
df_empresas_inactivas = pd.read_excel(
    "empresas.xlsx",
    sheet_name="inactivas",
    parse_dates=["fecha_alianza"]
)

df_empresas_inactivas.head(5)

,empresa_id,nombre_empresa,sector,ciudad,tamaño,presupuesto_salario_max,fecha_alianza
0,201,RetailCo Bogotá,Retail,Bogotá,Corporación,6000000,2022-11-01
1,202,Construcciones Tech,Construcción,Medellín,PYME,5500000,2022-12-15
2,203,Turismo Digital,Turismo,Cartagena,Startup,4500000,2023-01-10
3,204,MediaCo,Medios,Bogotá,Corporación,7000000,2023-03-22
4,205,BancaDigital SA,Finanzas,Bogotá,Corporación,10000000,2023-05-30

In [23]:
df_empresas_todas = pd.read_excel(
    "empresas.xlsx",
    sheet_name=None, 
    parse_dates=["fecha_alianza"]
)

df_empresas_todas

{'activas':    empresa_id      nombre_empresa         sector        ciudad       tamaño  \
 0         101    TechColombia SAS     Tecnología        Bogotá      Startup
 1         102  DataFlow Analytics     Tecnología      Medellín         PYME
 2         103  Innovación Digital     Tecnología        Bogotá  Corporación
 3         104      Fintech Andina       Finanzas        Bogotá         PYME
 4         105     CloudServ Latam     Tecnología          Cali      Startup
 5         106    Salud Digital CO          Salud      Medellín         PYME
 6         107    EduTech Colombia      Educación        Bogotá      Startup
 7         108     Logística Smart      Logística  Barranquilla  Corporación
 8         109            AgriData  Agroindustria          Cali         PYME
 9         110         CiberSegura     Tecnología        Bogotá      Startup

    presupuesto_salario_max fecha_alianza
 0                  8000000    2023-06-01
 1                  7500000    2023-08-15
 2                 12000000    2023-09-01
 3                  9000000    2023-10-20
 4                  6500000    2023-11-05
 5                  7000000    2024-01-10
 6                  5500000    2024-02-14
 7                  8500000    2024-03-01
 8                  6000000    2024-03-20
 9                  9500000    2024-04-01  ,
 'inactivas':    empresa_id       nombre_empresa        sector     ciudad       tamaño  \
 0         201      RetailCo Bogotá        Retail     Bogotá  Corporación
 1         202  Construcciones Tech  Construcción   Medellín         PYME
 2         203      Turismo Digital       Turismo  Cartagena      Startup
 3         204              MediaCo        Medios     Bogotá  Corporación
 4         205      BancaDigital SA      Finanzas     Bogotá  Corporación

    presupuesto_salario_max fecha_alianza
 0                  6000000    2022-11-01
 1                  5500000    2022-12-15
 2                  4500000    2023-01-10
 3                  7000000    2023-03-22
 4                 10000000    2023-05-30  }

In [27]:
#Exploración
print("Info del dataframe")
df_empresas_activas.info()

print("\nTipos de sector")
print(df_empresas_activas["sector"].value_counts())

Info del dataframe
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   empresa_id               10 non-null     int64
 1   nombre_empresa           10 non-null     str
 2   sector                   10 non-null     str
 3   ciudad                   10 non-null     str
 4   tamaño                   10 non-null     str
 5   presupuesto_salario_max  10 non-null     int64
 6   fecha_alianza            10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 692.0 bytes

Tipos de sector
sector
Tecnología       5
Finanzas         1
Salud            1
Educación        1
Logística        1
Agroindustria    1
Name: count, dtype: int64

In [32]:
#Promedio de valores numericos
promedio = df_empresas_activas["presupuesto_salario_max"].mean()
maximo = df_empresas_activas["presupuesto_salario_max"].max()
minimo = df_empresas_activas["presupuesto_salario_max"].min()

print(promedio,"%")
print("maximo: " , maximo)
print("minimo: " , minimo)

7950000.0 %
maximo:  12000000
minimo:  5500000

Formato Json = Javascript Object Notation

In [34]:
df_postulaciones = pd.read_json(
    "postulaciones.json",
    orient="records" #records = lista de objetos (cada {} = una fila)
)

df_postulaciones

,postulacion_id,candidato_id,empresa_id,fecha_postulacion,estado,puntaje_match
0,1001,1,101,2024-02-01,Seleccionado,92.5
1,1002,2,103,2024-02-05,Pendiente,78.0
2,1003,4,101,2024-02-10,Seleccionado,95.1
3,1004,6,107,2024-02-15,Rechazado,61.3
4,1005,7,102,2024-02-20,Seleccionado,88.7
5,1006,8,104,2024-02-22,Rechazado,55.0
6,1007,10,110,2024-03-01,Seleccionado,97.2
7,1008,11,105,2024-03-05,Pendiente,74.5
8,1009,13,103,2024-03-12,Pendiente,83.3
9,1010,14,108,2024-03-18,Rechazado,67.8
10,1011,16,102,2024-03-25,Seleccionado,91.0
11,1012,20,106,2024-04-02,Pendiente,80.4
12,1013,2,109,2024-04-05,Rechazado,58.2
13,1014,7,110,2024-04-10,Seleccionado,89.9
14,1015,1,104,2024-04-15,Pendiente,76.1

Bloque 4 - lectura SQL

In [37]:
#Sqlite
conexion = sqlite3.connect("datajobs.db")
print("Exito")

Exito

In [40]:
#Ver que tablas tenemos o tiene la base de datos

tablas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table'", conexion
)

print("Tablas disponibles en datajobs.db: ")
print(tablas)

Tablas disponibles en datajobs.db:
                 name
0  historial_salarios
1     certificaciones

In [41]:
#Traer de la db el historial de salarios

query01 = """
    SELECT * FROM historial_salarios
"""

df_salarios = pd.read_sql(query01, conexion)
df_salarios

,id,candidato_id,tecnologia,salario_actual,anios_experiencia,ciudad
0,1,1,Python,4200000,3,Bogotá
1,2,2,JavaScript,3600000,2,Medellín
2,3,4,Python,5900000,5,Bogotá
3,4,6,React,3000000,1,Medellín
4,5,7,Data Science,5500000,4,Bogotá
5,6,8,Python,4000000,3,Bucaramanga
6,7,10,DevOps,7000000,6,Bogotá
7,8,11,JavaScript,3900000,2,Medellín
8,9,13,Python,5200000,4,Bogotá
9,10,14,React,3700000,2,Cartagena
10,11,16,Data Science,6500000,5,Bogotá
11,12,17,DevOps,4900000,3,Medellín
12,13,20,Java,4500000,3,Medellín

In [45]:
#Top 5 candidatos con MAYOR salario_actual
#ORDER BY
#LIMIT 8

query_top5 = """
    SELECT *
    FROM historial_salarios
    ORDER BY salario_actual DESC
    LIMIT 5
"""

df_top5 = pd.read_sql(query_top5, conexion)
print("top 5 candidatos con mayor salario: ")
df_top5

top 5 candidatos con mayor salario:

   id  candidato_id    tecnologia  salario_actual  anios_experiencia  ciudad
0   7            10        DevOps         7000000                  6  Bogotá
1  11            16  Data Science         6500000                  5  Bogotá
2   3             4        Python         5900000                  5  Bogotá
3   5             7  Data Science         5500000                  4  Bogotá
4   9            13        Python         5200000                  4  Bogotá

In [46]:
#Candidatos que usen Python o Javascript
#IN
#WHERE

query_python_js = """
    SELECT *
    FROM historial_salarios
    WHERE tecnologia IN ('Python', 'JavaScript')
    ORDER BY salario_actual DESC
"""
df_python_js = pd.read_sql(query_python_js, conexion)
df_python_js

,id,candidato_id,tecnologia,salario_actual,anios_experiencia,ciudad
0,3,4,Python,5900000,5,Bogotá
1,9,13,Python,5200000,4,Bogotá
2,1,1,Python,4200000,3,Bogotá
3,6,8,Python,4000000,3,Bucaramanga
4,8,11,JavaScript,3900000,2,Medellín
5,2,2,JavaScript,3600000,2,Medellín